[package]
name = "trigger-timer"
version = "0.1.0"
authors = ["Spin Framework Contributors"]
edition = "2021"

[dependencies]
anyhow = "1.0.68"
clap = { version = "3.1.15", features = ["derive", "env"] }
serde = "1.0.188"
spin-factors = { path = "../../crates/factors" }
spin-runtime-factors = { path = "../../crates/runtime-factors" }
spin-trigger = { path = "../../crates/trigger" }
tokio = { version = "1", features = ["full"] }
tokio-scoped = "0.2.0"
wasmtime = { git = "https://github.com/bytecodealliance/wasmtime", rev = "8e22ff89" }

[workspace]
